### PR TITLE
JCL-384: Optimize request caching in session objects

### PR DESCRIPTION
**Pull request by acoburn**
At present, the caching mechanism compares the full URI in requests, but it should ignore any query parameters or hash fragments.

### CODE REVIEW

**Review by NSeydoux — APPROVED** [review]

**Review by langsamu — CHANGES_REQUESTED** [review]
OIDC [allows](https://openid.net/specs/openid-connect-core-1_0.html#Serializations) messages to be serialized as query strings.

Is this restriction on cache keys not too harsh (especially for the `OpenIdSession`)?

**Comment by acoburn** [comment]
> OIDC [allows](https://openid.net/specs/openid-connect-core-1_0.html#Serializations) messages to be serialized as query strings.

OIDC Messages are [defined](https://openid.net/specs/openid-connect-core-1_0.html#Terminology) as requests and responses sent between the RP (client) and OP (OpenID Provider). This PR has nothing to do with those messages: it is related to caching of credential values for requests between an RP and an RS (Resource Server).

**Comment by langsamu** [comment]
> > OIDC [allows](https://openid.net/specs/openid-connect-core-1_0.html#Serializations) messages to be serialized as query strings.
> 
> OIDC Messages are [defined](https://openid.net/specs/openid-connect-core-1_0.html#Terminology) as requests and responses sent between the RP (client) and OP (OpenID Provider). This PR has nothing to do with those messages: it is related to caching of credential values for requests between an RP and an RS (Resource Server).

I stand corrected.

But is the restriction not too harsh still? Resource Servers might well require different authentication depending on query string.

Even Solid, though the `OpenIdSession` is not specific to Solid.

**Comment by acoburn** [comment]
> But is the restriction not too harsh still? Resource Servers might well require different authentication depending on query string.

This is a good point. I've changed the implementation to only remove the fragment URI (if one exists)

**Review by langsamu — APPROVED** [review]

**Pull request merged**
